### ISSUE TITLE
Leaked GitHub credentials

### ISSUE THREAD

**Issue by joevanloon** [decentralizedlabs/pr-codex#5]
Client ID and secret are both exposed here: https://github.com/decentralizedlabs/pr-codex/blob/master/app/github/route.ts#L17-L18

These should be imported via environment variable and rotated, as per https://github.com/octokit/auth-app.js/#standalone-usage

**Comment by jacopo-eth** [comment]
Thanks for flagging @indigo-eth-sec! This has been fixed and credentials have been rotated
