### ISSUE TITLE
feat: markdown formatting

### ISSUE THREAD

**Issue by dalechyn** [decentralizedlabs/pr-codex#6]
Would be nice to see some `formatted code` as pr-codex sometimes references to the code functions objects etc

**Comment by jacopo-eth** [comment]
@h0tw4t3r makes sense. Could you link a comment to use as reference?

**Comment by dalechyn** [comment]
@jjranalli,

### Tldr
Added cookie-parser to package.json, added AuthGuard to auth.controller, added AuthService to auth.guard.spec.ts.

### Detailed summary

- Added "cookie-parser": "^1.4.6" to package.json
- Added AuthGuard to auth.controller.ts
- Added AuthService to auth.guard.spec.ts
- Imported CanActivate and AuthGuard to auth.controller.spec.ts
- Added a mockAuthGuard to auth.controller.spec.ts
- Modified getNonce() in auth.controller.ts to send response instead of returning string
- Modified auth() in auth.controller.ts to send true instead of empty response
- Added validate() and logout() methods to auth.controller.ts
- Implemented validate() method in auth.controller.ts to send true and set content type to text/plain
- Implemented logout() method in auth.controller.ts to send true and clear cookies
- Modified getNonce() in auth.controller.spec.ts to check response.send() is called with a string
- Modified auth() in auth.controller.spec.ts to check response.send() is called with true
- Implemented validate() method in auth.controller.spec.ts to check response.send() is called with true and content type is set to text/plain
- Implemented logout() method in auth.controller.spec.ts to check response.send() is called with true, content type is set to text/plain and cookies are cleared
- Imported Request and Response from express to auth.guard.spec.ts
- Modified canActivate() in auth.guard.ts to check if access token is valid and call canActivateViaRefreshToken() if it's not.
- Implemented canActivate() method in auth.guard.spec.ts to check if canActivateViaRefreshToken() is called when access token is invalid.

> The following files were skipped due to too many changes: pnpm-lock.yaml.

**Comment by jacopo-eth** [comment]
To make sure I understand this, it appears that in most comments it uses backticks to format filenames (ie https://github.com/transmissions11/flux/pull/63#issuecomment-1497971347). However in the comment shared above this doesn't seem to be happening. So is it not consistent?

**Comment by dalechyn** [comment]
> To make sure I understand this, it appears that in most comments it uses backticks to format filenames (ie https://github.com/transmissions11/flux/pull/63#issuecomment-1497971347). However in the comment shared above this doesn't seem to be happening. So is it not consistent?

Yeah, you're absolutely right, it is not consistent.

I don't really know, maybe we should lower the temperature and tell it a bit more forcefully to style code?

![image](https://user-images.githubusercontent.com/35642018/230402272-3359b704-1ab7-42f9-a848-c040e7403513.jpeg)

**Comment by jacopo-eth** [comment]
@h0tw4t3r Let's see if #7 works, and if that's not enough we can try lowering temp. If the comment shared above is in one of your repos, can you push a commit and see how does the new pr-codex comment look?

**Comment by jacopo-eth** [comment]
closing this for now, feel free to reopen if needed
